[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel"
]

[project]
name = "demo_coding_classroom"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
