name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Challenge 1
      id: challenge-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Challenge 1
        setup-command: pip install -U pip pytest && pip install -e .
        command: pytest test/challenge1.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHALLENGE-1_RESULTS: "${{steps.challenge-1.outputs.result}}"
      with:
        runners: challenge-1
